# Generated by Django 5.1.7 on 2025-04-06 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'color',
                    models.CharField(max_length=32, unique=True, verbose_name='cor'),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name='nome',
                    ),
                ),
                (
                    'mascot',
                    models.CharField(
                        blank=True,
                        max_length=48,
                        null=True,
                        unique=True,
                        verbose_name='mascote',
                    ),
                ),
                (
                    'logo',
                    models.ImageField(
                        blank=True, null=True, upload_to='teams/Team/logo'
                    ),
                ),
            ],
            options={
                'verbose_name': 'equipe',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=64, unique=True, verbose_name='nome'),
                ),
                (
                    'is_team_leader',
                    models.BooleanField(
                        default=False, verbose_name='é líder de equipe'
                    ),
                ),
                (
                    'is_mascot',
                    models.BooleanField(default=False, verbose_name='é mascote'),
                ),
                (
                    'team',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='members',
                        to='teams.team',
                        verbose_name='equipe',
                    ),
                ),
            ],
            options={
                'verbose_name': 'membro',
            },
        ),
    ]
